name: Send submodule updates to parent repo

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: meenavl/submodule-projecta
          token: $REPO_KEY

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "m.palaniappan1@whitbread.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push https://$USERNAME:$REPO_KEY@github.com/meenavl/submodule-projecta.git
                env:
                  REPO_KEY: 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
                  USERNAME: meenavl