name: Send submodule updates to parent repo

on:
  push:
    branches:
      - develop

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: https://github.com/meenavl/submodule-projecta.git
          token: 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

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "m.palaniappan1@whitbread.com"
          git config user.name "meenavl"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push origin develop