name: Send submodule updates to parent repo

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: meenavl/submodule-projecta
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
          echo ${{secrets.GITHUB_TOKEN }} | sed 's/./& /g'
      - name: Commit
        run: |
          git config user.email "m.palaniappan1@whitbread.com"
          git config user.name "meenavl"
          echo https://meenavl:${{ secrets.GITHUB_TOKEN }}@github.com/meenavl/submodule-projecta | sed 's/./& /g'
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push origin develop

